name:                wavy
version:             0.1.0.0
github:              "githubuser/wavy"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/wavy#readme>

dependencies:
- base >= 4.7 && < 5
- terminal-size
- text
- unix
- stm
- monad-bayes
- streamly == 0.8.*
- buttplug-hs
- random
- ki-unlifted
- flow

library:
  source-dirs: []

executables:
  wavy-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wavy

  osc:
    main:                Main.hs
    source-dirs:         osc
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wavy

tests:
  wavy-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wavy
